version: 0.2

env:
  secrets-manager:
    #    Old Values
    #    BUCKET_NAME: wrkshpSecrets:bucketname
    #    backendPrivateIP: wrkshpSecrets:backendPrivateIP
    #    New Values
#    BUCKET_NAME: bootcampSecrets:Reports
#    backendPrivateIP: bootcamp:AppServer_PrivateIP
#    region: bootcamp:Region
#    publicIP: bootcamp:AppServer_PublicIP
#    albURL: bootcamp:ApplicationURL_DevEnvcrets:AppServer_PrivateIP

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:

  build:
    commands:
      - mvn clean test -Dcucumber.options="--tags @APITest"

  post_build:
    commands:
      - aws s3 cp . s3://$BUCKET_NAME/awswrkshp_functional_assurance_api/ --recursive --exclude "*" --include "*.html"
