version: 0.2

env:
  secrets-manager:
    #    Old Values
    #    BUCKET_NAME: wrkshpSecrets:bucketname
    #    backendPrivateIP: wrkshpSecrets:backendPrivateIP
    #    New Values
    BUCKET_NAME: wrkshpSecrets:Reports
    backendPrivateIP: wrkshpSecrets:AppServer_PrivateIP

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:

  build:
    commands:
      - mvn clean test -Dcucumber.options="--tags @UITest" -DExecutionPlatform="AWS_CHROME"

  post_build:
    commands:
      - aws s3 cp . s3://$BUCKET_NAME/awswrkshp_functional_assurance_ui/ --recursive --exclude "*" --include "*.html"
